name: Build and Publish CI
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build and Publish Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.5
        with:
          poetry-version: 1.1.14
      - name: Install the package
        run: poetry install -vvv
      - name: Build the package
        run: poetry build
      - name: Publish the package to PyPi
        run: poetry publish --username "__token__" --password "{{ secrets.PYPI_TOKEN }}" --dry-run
