name: Build and Publish CI
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build and Publish Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the package
        run: poetry install -vvv
      - name: Set up the Poetry config
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Build and publish the package to PyPi
        run: poetry publish --build
